// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNuW_NTKkQUdGkglsFV9CyARlgJ9WibXE',
    appId: '1:994293928667:web:602666df794c06bd5ff2fe',
    messagingSenderId: '994293928667',
    projectId: 'dobae-platform',
    authDomain: 'dobae-platform.firebaseapp.com',
    storageBucket: 'dobae-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCdEZcZ1NnKimCyDkQEVjTmTxqTHsmmk',
    appId: '1:994293928667:android:d68094a8fa98f8635ff2fe',
    messagingSenderId: '994293928667',
    projectId: 'dobae-platform',
    storageBucket: 'dobae-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPcdUxh5supUxn_nQ6zRYSHQKWveQPK4',
    appId: '1:994293928667:ios:b274a63e007214015ff2fe',
    messagingSenderId: '994293928667',
    projectId: 'dobae-platform',
    storageBucket: 'dobae-platform.firebasestorage.app',
    iosBundleId: 'com.example.dobaePlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPcdUxh5supUxn_nQ6zRYSHQKWveQPK4',
    appId: '1:994293928667:ios:b274a63e007214015ff2fe',
    messagingSenderId: '994293928667',
    projectId: 'dobae-platform',
    storageBucket: 'dobae-platform.firebasestorage.app',
    iosBundleId: 'com.example.dobaePlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNuW_NTKkQUdGkglsFV9CyARlgJ9WibXE',
    appId: '1:994293928667:web:724f1dbc56b85fad5ff2fe',
    messagingSenderId: '994293928667',
    projectId: 'dobae-platform',
    authDomain: 'dobae-platform.firebaseapp.com',
    storageBucket: 'dobae-platform.firebasestorage.app',
  );
}
